### ISSUE TITLE
LagIter' object has no attribute 'ports'

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#413]
def tgen_capacity(routes):
        conv_config = cvg_api.convergence_config()
        config = conv_config.config
        for i in range(1,port_count+1):
            config.ports.port(name = 'Test_Port_%d'%i,location = tgen_ports[i-1]['location'])
            c_lag=config.lags.lag(name="lag%d"%i)
>           lp=c_lag.ports.port(port_name='Test_Port_%d'%i)
E           AttributeError: 'LagIter' object has no attribute 'ports'

**Comment by Rangababu-R** [comment]
@selldinesh 
please add the index to lag
c_lag=config.lags.lag(name="lag%d"%i)[-1]

**Comment by selldinesh** [comment]
@Rangababu-R Added       c_lag=config.lags.lag(name="lag%d"%i)[-1] and the getting below error 
  for i in range(1,port_count+1):
            config.ports.port(name = 'Test_Port_%d'%i,location = tgen_ports[i-1]['location'])
            c_lag = config.lags.lag(name="lag%d" % i)[-1]
            lp = c_lag.ports.port(port_name='Test_Port_%d' % i)
>           lp.protocol.static.lag_id = i
E           AttributeError: 'LagPortIter' object has no attribute 'protocol'

**Comment by Rangababu-R** [comment]
@selldinesh, 1st error was with LagIter, which is fixed by indexing
this time the error is for LapPortIter, same approach for the below statement.
 lp = c_lag.ports.port(port_name='Test_Port_%d' % i)[-1]
 
 config.lags.lag() will return lagIter as we can have any number of lag objects in one statement
 ex: config.lags.lag().lag().lag() --> config.lags.lag()<returns lagIter>.lag()<returns lagIter>
       to grab the lag or the item of any snappiIter object you will have to use in the below ways
       for single object instance
       lag = config.lags.lag()[-1]
       for multiple obj instances
       l1, l2 = config.lags.lag().lag()
same applies to all the snappiIters and its item instances

**Comment by selldinesh** [comment]
Thanks @Rangababu-R , it worked
