### ISSUE TITLE
Support needed to send ping from IPv4 devices

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-ixnetwork#435]
**Is your feature request related to a use case? Please describe.**
A clear and concise description of what the use case is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ANISH-GOTTAPU** [comment]
@ashutshkumr 

As per discussion with Kamal we can achieve this in two approaches

approach-1:
-------------
**Add ping Functionality at device level, have to update the models to support this.**

approach-2:
-------------
**Create a flow with ICMP echo request, as of now model supports adding ICMP packet but ixnetwork concrete implementation is not available yet.**



_For either approaches we need modeling changes to add ping statistics to port metrics_

![image](https://user-images.githubusercontent.com/48308607/131796420-a4e205c3-292e-418d-b425-d338ceea5e6a.png)

**Comment by ashutshkumr** [comment]
@ajbalogh which approach should we go with here. Do you have any other ideas ?

**Comment by ashutshkumr** [comment]
@ankur-sheth @winstonliu1111 FYI

@selldinesh 

Since we're discussing the approaches here, before diving into actual modelling changes, I have one more thoughts on metrics.

- I would prefer exposing new metrics instead of exposing ping-related info in port metrics.
- We need to confirm if this is something maintained for each interface or do we expsose cumulative stats
- Since the purpose was to measure "the time it takes to get the first ping response", are users supposed to calculate it by polling ping metrics ? (for snappi-ixnetwork implementation specifically, accuracy will be lost, since each call to get ping metrics might elapse ~1-2 seconds)

**Comment by ajbalogh** [comment]
@ashutshkumr I lean towards approach number 2 as it fulfills the idea of using the product as intended.
Long story form...
If I'm using a product that generates standard/non-standard packets why would the product offer two ways send icmp packets?  The only thing I can think of is one way is too slow (implementation) and then a customer can choose to use a different product.

**Comment by winstonliu1111** [comment]
What is the use case or experiment/test requiring this?  We should understand the intent better.  

Usually ping is just a quick diag facility to get an idea on rtt and connectivity.  Do we have a test requirement to measure RTT?  What is it?

If that is the intent why not just use good old ping?

**Comment by winstonliu1111** [comment]
If diag is the use case, why wouldn't this be some kind of diag control/action that dont need to be dealing with polling stats in another place?

**Comment by ajbalogh** [comment]
@selldinesh please fill in the original issue comment with details. I've added the template sections that need to be addressed.

**Comment by ashutshkumr** [comment]
Implementation will start per model changes in https://github.com/open-traffic-generator/models/pull/163

**Comment by ANISH-GOTTAPU** [comment]
Support available in snappi[ixnetwork, convergence]==0.5.8
