### ISSUE TITLE
Add Manual Gateway MAC support 

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/snappi-ixnetwork#555]
Add Manual Gateway MAC support

**Comment by mgheorghe** [comment]
normally traffic will be sent to the mac of the interface. but in our sonic datacenter scenario in order to implement redundancy, they do not care on what interface the traffic is being received, so the packets are always sent to the device mac not the interface mac. 
https://github.com/sonic-net/SONiC/wiki/Configuration
{
```
"DEVICE_METADATA": {
        "localhost": {
        "hwsku": "Force10-S6100",
        "synchronous_mode": "disable",
        "default_bgp_status": "up",
        "docker_routing_config_mode": "unified",
        "hostname": "sonic-s6100-01",
        "platform": "x86_64-dell_s6100_c2538-r0",
        "mac": "4c:76:25:f4:70:82",
        "default_pfcwd_status": "disable",
        "bgp_asn": "65100",
        "deployment_id": "1",
        "type": "ToRRouter"
    }
  }
}
```

from our side only way we were able to do this was to disable arp and set manual gateway mac as the mac of the device 
"mac": "4c:76:25:f4:70:82",
also the traffic is not sent to the IP of the physical interface it is sent to the ip of the loopback interface.
